version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: docjaegr
    container_name: conjaegr    
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: mysql:5.7.41
    container_name: docmysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sitedb
      MYSQL_ROOT_PASSWORD: root